### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by aakoch** [rabee2050/esp32-kit#1]
Code is too big. Without any changes, I get this error:
```
Sketch uses 1328693 bytes (101%) of program storage space. Maximum is 1310720 bytes.text section exceeds available space in board

Global variables use 44564 bytes (13%) of dynamic memory, leaving 283116 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
Error compiling for board ESP32 Dev Module.
```

**Comment by aakoch** [comment]
My guess is I have newer libraries that are larger.

#include <WiFi.h>
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>
#include <BLE2902.h>

**Comment by aakoch** [comment]
Using a different partition scheme gets around it

**Comment by aakoch** [comment]
Or I can't read instructions.

**Comment by rabee2050** [comment]
There are some notes in the Arduino sketch, please follow these instructions to avoid this issue.

Best Regards
Rabee
________________________________
